server {
    # Nginx escuchará en el puerto 8080.
    listen 8080;
    listen [::]:8080;

    # La raíz donde se encuentran nuestros archivos.
    root /usr/share/nginx/html;

    # El archivo principal a servir.
    index index.html;

    # --- LA MAGIA PARA VUE ---
    # Esta es la directiva más importante para una SPA.
    # Le dice a Nginx: "Intenta encontrar el archivo que te piden ($uri).
    # Si no lo encuentras como archivo, intenta ver si es una carpeta ($uri/).
    # Si sigues sin encontrar nada, en lugar de dar un error 404,
    # simplemente sirve el archivo /index.html".
    # Esto le devuelve el control a Vue Router para que maneje la ruta.
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Configuración para que los logs sean más útiles en OpenShift/Kubernetes
    # y vayan a la salida estándar para que 'oc logs' los capture.
    error_log /dev/stdout info;
    access_log /dev/stdout;
}