export const columns = [
  { field: 'id', header: 'ID OT FALLIDAS', hidden: true, exportable: false, filter: false },
  { field: 'nroOrdenTrabajo', header: 'Nro. OT', hidden: false, exportable: true, filter: true, sort: true },
  { field: 'fechaCierre', header: 'FECHA CIERRE', hidden: false, exportable: true, filter: true, sort: true },
  { field: 'tareaCodigo', header: 'COD TAREA', hidden: false, exportable: true, filter: true, sort: true },
  { field: 'direccion', header: 'DIRECCION', hidden: false, exportable: true, filter: true, sort: true },
  { field: 'ciudad', header: 'CIUDAD', hidden: false, exportable: true, filter: true, sort: true },
  { field: 'provincia', header: 'PROVINCIA', hidden: false, exportable: true, filter: true, sort: true },
  { field: 'region', header: 'REGION', hidden: false, exportable: true, filter: true, sort: true },
  { field: 'pais', header: 'PAIS', hidden: false, exportable: true, filter: true, sort: true },
  { field: 'contratista', header: 'CONTRATISTA', hidden: false, exportable: true, filter: true, sort: true },
  { field: 'tecnicoCierre', header: 'TECNICO CIERRE', hidden: false, exportable: true, filter: true, sort: true },
  { field: 'actividades', header: 'ACTIVIDADES', hidden: false, exportable: true, filter: true, sort: true },
  { field: 'sistemaOrigen', header: 'SISTEMA ORIGEN', hidden: false, exportable: true, filter: true, sort: true },
  { field: 'errorDescripcion', header: 'DESCRIPCION ERROR', hidden: false, exportable: true, filter: true, sort: true },
  { field: 'excluida', header: 'EXCLUIDA', hidden: false, exportable: true, filter: true, sort: true },
  { field: 'motivoExclusion', header: 'MOTIVO EXCLUSION', hidden: false, exportable: true, filter: true, sort: true },
  { field: 'nota', header: 'NOTA', hidden: true, exportable: true, filter: false },
  { field: 'tieneNota', header: 'NOTA', hidden: false, exportable: false, filter: false, sort: false },
  { field: 'incluirExp', header: 'INCLUIR', hidden: true, exportable: false, filter: false },
  { field: 'incluir', header: 'INCLUIR', hidden: false, exportable: false, filter: false, sort: false }
]
