export const columns = [
  { field: 'id', header: 'ID OT FALLIDAS', hidden: true, exportable: false, filter: false, sort: false },
  { field: 'nroOrdenTrabajo', header: 'NRO. OT', hidden: false, exportable: true, filter: true, sort: true, width: '112px', minWidth: '48px' },
  { field: 'fechaCierre', header: 'FECHA CIERRE', hidden: false, exportable: true, filter: true, sort: true, width: '118px', minWidth: '48px' },
  { field: 'tareaCodigo', header: 'COD TAREA', hidden: false, exportable: true, filter: true, sort: true, width: '88px', minWidth: '48px' },
  { field: 'direccion', header: 'DIRECCION', hidden: false, exportable: true, filter: true, sort: true, width: '138px', minWidth: '48px' },
  { field: 'ciudad', header: 'CIUDAD', hidden: false, exportable: true, filter: true, sort: true, width: '100px', minWidth: '48px' },
  { field: 'provincia', header: 'PROVINCIA', hidden: false, exportable: true, filter: true, sort: true, width: '108px', minWidth: '48px' },
  { field: 'region', header: 'REGION', hidden: false, exportable: true, filter: true, sort: true, width: '92px', minWidth: '48px' },
  { field: 'pais', header: 'PAIS', hidden: false, exportable: true, filter: true, sort: true, width: '62px', minWidth: '48px' },
  { field: 'contratista', header: 'CONTRATISTA', hidden: false, exportable: true, filter: true, sort: true, width: '140px', minWidth: '48px' },
  { field: 'tecnicoCierre', header: 'TECNICO CIERRE', hidden: false, exportable: true, filter: true, sort: true, width: '110px', minWidth: '48px' },
  { field: 'actividades', header: 'ACTIVIDADES', hidden: false, exportable: true, filter: true, sort: true, width: '140px', minWidth: '48px' },
  { field: 'sistemaOrigen', header: 'SISTEMA ORIGEN', hidden: false, exportable: true, filter: true, sort: true, width: '105px', minWidth: '48px' },
  { field: 'errorDescripcion', header: 'DESCRIPCION ERROR', hidden: false, exportable: true, filter: true, sort: true, width: '115px', minWidth: '48px' },
  { field: 'excluida', header: 'EXCLUIDA', hidden: false, exportable: true, filter: true, sort: true, width: '82px', minWidth: '48px' },
  { field: 'motivoExclusion', header: 'MOTIVO_EXCLUSION', hidden: false, exportable: true, filter: true, sort: true, width: '132px', minWidth: '48px' },
  { field: 'nota', header: 'NOTA', hidden: true, exportable: true, filter: false, sort: false },
  { field: 'tieneNota', header: 'NOTA', hidden: false, exportable: false, filter: false, sort: false, width: '62px', minWidth: '48px' },
  { field: 'incluirExp', header: 'INCLUIR', hidden: true, exportable: false, filter: false, sort: false },
  { field: 'incluir', header: 'INCLUIR', hidden: false, exportable: false, filter: false, sort: false, width: '62px', minWidth: '48px' }
]
