export const columns = [
  { field: 'id', header: 'ID OT Fallidas', hidden: true, exportable: false, filter: false, sort: false },
  { field: 'nroOrdenTrabajo', header: 'Nro. OT', exportHeader: 'NRO. OT', hidden: false, exportable: true, filter: true, sort: true, width: '112px', minWidth: '48px' },
  { field: 'fechaCierre', header: 'Fecha Cierre', exportHeader: 'FECHA CIERRE', hidden: false, exportable: true, filter: true, sort: true, width: '118px', minWidth: '48px' },
  { field: 'tareaCodigo', header: 'Cod. Tarea', exportHeader: 'COD TAREA', hidden: false, exportable: true, filter: true, sort: true, width: '88px', minWidth: '48px' },
  { field: 'direccion', header: 'Dirección', exportHeader: 'DIRECCION', hidden: false, exportable: true, filter: true, sort: true, width: '138px', minWidth: '48px' },
  { field: 'ciudad', header: 'Ciudad', exportHeader: 'CIUDAD', hidden: false, exportable: true, filter: true, sort: true, width: '100px', minWidth: '48px' },
  { field: 'provincia', header: 'Provincia', exportHeader: 'PROVINCIA', hidden: false, exportable: true, filter: true, sort: true, width: '108px', minWidth: '48px' },
  { field: 'region', header: 'Región', exportHeader: 'REGION', hidden: false, exportable: true, filter: true, sort: true, width: '92px', minWidth: '48px' },
  { field: 'pais', header: 'País', exportHeader: 'PAIS', hidden: false, exportable: true, filter: true, sort: true, width: '62px', minWidth: '48px' },
  { field: 'contratista', header: 'Contratista', exportHeader: 'CONTRATISTA', hidden: false, exportable: true, filter: true, sort: true, width: '140px', minWidth: '48px' },
  { field: 'tecnicoCierre', header: 'Técnico Cierre', exportHeader: 'TECNICO CIERRE', hidden: false, exportable: true, filter: true, sort: true, width: '110px', minWidth: '48px' },
  { field: 'actividades', header: 'Actividades', exportHeader: 'ACTIVIDADES', hidden: false, exportable: true, filter: true, sort: true, width: '140px', minWidth: '48px' },
  { field: 'sistemaOrigen', header: 'Sistema Origen', exportHeader: 'SISTEMA ORIGEN', hidden: false, exportable: true, filter: true, sort: true, width: '105px', minWidth: '48px' },
  { field: 'errorDescripcion', header: 'Descripción Error', exportHeader: 'DESCRIPCION ERROR', hidden: false, exportable: true, filter: true, sort: true, width: '115px', minWidth: '48px' },
  { field: 'excluida', header: 'Excluida', exportHeader: 'EXCLUIDA', hidden: false, exportable: true, filter: true, sort: true, width: '82px', minWidth: '48px' },
  { field: 'motivoExclusion', header: 'Motivo Exclusión', exportHeader: 'MOTIVO_EXCLUSION', hidden: false, exportable: true, filter: true, sort: true, width: '132px', minWidth: '48px' },
  { field: 'nota', header: 'Nota', exportHeader: 'NOTA', hidden: true, exportable: true, filter: false, sort: false },
  { field: 'tieneNota', header: 'Nota', hidden: false, exportable: false, filter: false, sort: false, width: '62px', minWidth: '48px' },
  { field: 'incluirExp', header: 'Incluir', hidden: true, exportable: false, filter: false, sort: false },
  { field: 'incluir', header: 'Incluir', hidden: false, exportable: false, filter: false, sort: false, width: '62px', minWidth: '48px' }
]
